// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHVvee4uAQEQDdDQiet54Fd8HIsMCnk4',
    appId: '1:848068157713:web:397452aef6a5e3c973ecb0',
    messagingSenderId: '848068157713',
    projectId: 'bahar-e-aqeedat',
    authDomain: 'bahar-e-aqeedat.firebaseapp.com',
    storageBucket: 'bahar-e-aqeedat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCBt1zppafaLjIhpeYKNL3l2WsNY9GjU',
    appId: '1:848068157713:android:d2a20045ea7d592373ecb0',
    messagingSenderId: '848068157713',
    projectId: 'bahar-e-aqeedat',
    storageBucket: 'bahar-e-aqeedat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8irvJ6SDcuDClHNNA0tNopxGH3BL0LYM',
    appId: '1:848068157713:ios:a1c3132c52d8a6f473ecb0',
    messagingSenderId: '848068157713',
    projectId: 'bahar-e-aqeedat',
    storageBucket: 'bahar-e-aqeedat.firebasestorage.app',
    iosClientId: '848068157713-cbhc7egh24b2sv39jo3hrbggu85qt5m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.baharEAqeedat',
  );
}
